# Generated by Django 2.2.4 on 2022-06-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist_app', '0002_auto_20220626_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
    ]
